name: Deploy to GitHub Pages
on:
  push:
    branches:
      - main 
jobs:
  test:
    name: Run application tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Install dependencies
        run: npm ci
      
      - name: Build project
        run: npm run build

      - name: Test project
        run: npm run test-ci
  publish:
    name: Publish to github
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: ./scripts/build.sh

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GH_SECRET_TOKEN }}
          publish_dir: ./dist
          publish_branch: gh-pages 

